USE delivery;

CREATE TABLE users(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(180) NOT NULL UNIQUE,
 password VARCHAR(90),
 name VARCHAR(90) NOT NULL,
 lastname VARCHAR(90) NOT NULL,
 phone VARCHAR(90) NOT NULL UNIQUE,
 image VARCHAR(255) NULL,
 created_at TIMESTAMP(0) NOT NULL,
 updated_at TIMESTAMP(0) NOT NULL
);